DROP TABLE IF EXISTS month_dim;
CREATE TABLE month_dim (
monthID INTEGER PRIMARY KEY AUTOINCREMENT,
quarterID INTEGER,
month INTEGER
);

DROP TABLE IF EXISTS year_dim;
CREATE TABLE year_dim (
yearID INTEGER PRIMARY KEY AUTOINCREMENT,
year INTEGER
);

DROP TABLE IF EXISTS quarter_dim;
CREATE TABLE quarter_dim (
quarterID INTEGER PRIMARY KEY AUTOINCREMENT,
yearID INTEGER,
quarter INTEGER
);

DROP TABLE IF EXISTS day_dim;
CREATE TABLE day_dim (
dayID INTEGER PRIMARY KEY AUTOINCREMENT,
datum date,
weekID INTEGER,
monthID INTEGER,
day INTEGER
);

DROP TABLE IF EXISTS week_dim;
CREATE TABLE week_dim (
weekID INTEGER PRIMARY KEY AUTOINCREMENT,
week INTEGER
);